### ISSUE TITLE
CQ root context parameter not supported

### ISSUE THREAD

**Issue by bdhoine** [shsteimer/IntelliVault#12]
When starting AEM with the parameter -Dorg.apache.felix.http.context_path="/NEWROOT" then the plugin is not working when setting the server to http://localhost:4502/NEWROOT.

**Comment by rehseboy** [comment]
I had the same problem. The issue is with vlt, as far as I can tell. You can work around by using:

http://localhost:4502/NEWROOT/crx/server/crx.default

as your CRX Repository URL
