### ISSUE TITLE
TOP_LEVEL_JCR_PATHS

### ISSUE THREAD

**Issue by grahampaulcook** [shsteimer/IntelliVault#13]
Hi

What is the reason for not being able to import/export from a top level directory? 

https://github.com/shsteimer/IntelliVault/blob/master/src/com/razorfish/platforms/intellivault/services/impl/IntelliVaultServiceImpl.java#L81

Thanks

**Comment by ghost** [comment]
I honestly don't remember why I added that.  I think I had some crashes when doing large operations, and making top level paths not possible seemed like a reasonable way to avoid that.  I'll try removing that check for the next release and see how it goes

**Comment by shsteimer** [comment]
this check is removed in the latest release
