### ISSUE TITLE
Auto Sync on Save fir ui.apps & ui.content files

### ISSUE THREAD

**Issue by shaun-teknop** [shsteimer/IntelliVault#18]
Hi,

I want auto sync feature like VaultClipse in latest version where it is able to auto synce ui.apps & ui.content directory's contents to CRX via vault.
How can I achieve same functionality using this plugin.

Awaiting for reply...

Thanks in advance!

**Comment by shsteimer** [comment]
I have non intention of implementing this, nor would I really want it as part of this plugin.  That's really a different model of operating than what this plugin aims to enable.
