### ISSUE TITLE
Not Showing in tool bar

### ISSUE THREAD

**Issue by ArnieKebs** [shsteimer/IntelliVault#19]
Is there a compatibility issue in using this plug in? I can't coz I can't see it in my tool bar. I am now currently using IntelliJ 2016.1.4. Please help.

**Comment by shsteimer** [comment]
Can you clarify what you mean by the toolbar?  The plugin should surface in 2 places

1.  configure the plugin at IntelliJ IDEA -> Preferences -> Tools - > IntelliVault
2.  In the context menu when you right click on a folder or file in the project view

**Comment by ArnieKebs** [comment]
I see. I saw it. Thanks. Do you have tutorial documentation on how to set it up and use it? Thank you very much.

**Comment by ArnieKebs** [comment]
Got it :D I just finished on setting it up. :D
