### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by performantp** [shsteimer/IntelliVault#2]
Is there a short description on how to use the thing?

**Comment by smbgood** [comment]
@performantp You'll need to edit the Settings in IntelliJ to point it to where you have vault located, then right click a file or folder structure you want to push/pull, hover over IntelliVault and select push to or pull from CRX. My path was something like "C:\Adobe\CQ\author\cq5_wcm\crx-quickstart\opt\filevault\vault-cli-2.4.18"

**Comment by shsteimer** [comment]
Most likely, this just needs to exist in the form of a better README file with instructions on setup and usage.

**Comment by ghost** [comment]
Documentation is part of the code, so unless there is at least a basic readme about how to get this to work, the plugin should be considered **broken**.

**Comment by shsteimer** [comment]
@elFua Fair enough, and I'm happy to acknowledge the need for better documentation.  But it really is fairly straight forward to set up and use.  Considering that, plus the fact that it was originally created to scratch a personal itch...better documentation hasn't exactly been a priority.  

If someone wants to document how to use and submit a PR for it, I'd be happy to merge it in.

**Comment by ghost** [comment]
@shsteimer: I am ready to be that someone who will write the readme, provided that I can figure out a way to get the plugin to work. In the current Intellij 14.0.3 Ultimate I don't even see _any_ configuration dialog at all. Typing `intellivault` in **Preferences** only displays the **Plugins** section which only offers the option to uninstall the plugin. The configuration dialog is nowhere to be seen.

**Comment by smbgood** [comment]
@elFua  File -> Settings (CTRL+ALT+S) -> Other Settings (at the bottom) -> Intellivault. There you go.

**Comment by ghost** [comment]
@smbgood: After latest update **IntelliVault** finally appeared under _Other Settings_! Thank you very much sir! It finally works! The plugin saves me a ton of time - no need anymore to have Eclipse running just in order to quickly deploy some XML changes. This is way faster than running maven deploy just in order to update some XML changes. Very much appreciated!

**Comment by helmutgranda** [comment]
@elFua - where is the documentation that you were ready to write ;). Also you can take a look at VLT which comes pre-packaged with AEM or Brackets which supports CRX synchronization with the installation of a plugin.

@smbgood - this plugin was installed on WebStorm but there are no "other settings" option (again for WebStorm only), do you know if there is a flag that needs to be set in order for this tool to work on WebStorm?

**Comment by elFua** [comment]
@smbgood: could you please update the README.md from https://github.com/elFua/IntelliVault/blob/master/README.md

**Comment by shsteimer** [comment]
@elFua @smbgood 

please send a pull request and I can take a look.

**Comment by Gundalf72** [comment]
I had no issues with the configuration, but I was stumped for a short while due to the "Pull from CRX" context menu being disabled. I was assuming right-clicking a folder within my project, IntelliVault --> Pull from CRX would work in any context. However it only becomes active in folders below jcr_root.

So from jcr_root/content; jcr_root/apps; jcr_root/content/my_site etc.

Works beautifully.

**Comment by dantintle** [comment]
Thank you, @Gundalf72 Was driving myself crazy today trying to figure out what I did wrong on the install.

**Comment by dmitry-tikva** [comment]
Will it work with WebStorm? 

WebStorm 2016.2.3
Build #WS-162.1812.21, built on September 4, 2016
Expiration date: November 12, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I can't see "Other Settings" in the preferences, after install this plugin...
Could you help pls?
Thanks a lot! :)

**Comment by 14rego** [comment]
I'm also not able to find somewhere to configure this:
- Preferences
- Preferences > Plugins
- Preferences > Other Settings
- File > Other Settings
- etc.

I can see IntelliVault in the context menu for my files, but it's disabled.

```
IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
Licensed to IntelliJ IDEA Evaluator
Expiration date: May 28, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6
```
