### ISSUE TITLE
Vault is exporting jcr:mixinTypes property even when jcr is missing this property

### ISSUE THREAD

**Issue by bsaravanaprakash** [shsteimer/IntelliVault#21]
When I run 'Pull from CRX', the export creates an empty jcr:mixinTypes property in output .content.xml
![image](https://user-images.githubusercontent.com/14592489/39062143-9b03a44a-4494-11e8-92d7-eb2260746d22.png)

But corresponding node in jcr is missing this property:
![image](https://user-images.githubusercontent.com/14592489/39062297-20f35ba4-4495-11e8-856e-08d7e7cfb7bb.png)

I am using 
AEM 6.3 SP1 
vault-cli-3.1.6
IntelliVault - 0.10.0

Why does intellivault export properties that are not added in jcr?

**Comment by shsteimer** [comment]
I think you are looking at the wrong node in crx-de.  your screen shot shows the properties of the parent node, but the jcr:mixinTypes property is on the jcr:content node.  Please validate you are looking in the right place.

Also, the plugin simply shells out to vlt under the covers, so if this is an issue, it's with VLT not this plugin, so there really isn't anything I can do to fix it.
