### ISSUE TITLE
ClassNotFound Exception when trying to pull from CRX

### ISSUE THREAD

**Issue by deepkamal** [shsteimer/IntelliVault#22]
Error Screen Shot: 
![image](https://user-images.githubusercontent.com/7984303/39853957-e0dc427a-5442-11e8-8757-a8a3b7863b0d.png)

Version of Plugin and other details:
![image](https://user-images.githubusercontent.com/7984303/39854024-37fee2ec-5443-11e8-9e34-1bac2fad88d9.png)

IntelliJ version:
![image](https://user-images.githubusercontent.com/7984303/39854050-5cf71c0e-5443-11e8-8b3a-5550cc0f7610.png)

This is similar to #7 , however #7 is about old AEM version, and the issue is fixed too - I have AEM 6.4, 
please suggest if something is missing somewhere.

**Comment by sergikoff** [comment]
I have the same issue

**Comment by sergioly** [comment]
@deepkamal I had the same issue but with AEM 6.3 version. It was caused by improperly configured "Vault Directory" setting. Path should not contain "/" at the end.
Example: `.../crx-quickstart/opt/filevault/vault-cli-3.1.38/bin`.
Hope this will helps

**Comment by deepkamal** [comment]
thanks a lot for your help in pointing out this trivial thing @sergikoff , in AEM6.4 there was no fileVault folder, i copied from my 6.3 base and now it seems to be exporting fine, will do more tests and open issues if found, closing this for now.
