### ISSUE TITLE
java.lang.ClassNotFoundException: com/day/jcr/vault/cli/VaultFsApp

### ISSUE THREAD

**Issue by foxted** [shsteimer/IntelliVault#25]
Experiencing an issue pulling from CRX. here's my setup:

IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

When trying to pull from CRX, I get the `java.lang.ClassNotFoundException: com/day/jcr/vault/cli/VaultFsApp` exception.

Using vlt in command line with same arguments works fine.

**Comment by shsteimer** [comment]
What version of vlt does your configuration point to?  Can you go in the vault lib directory and look for a jar file named something similar to vault-vlt-3.1.38.jar?

There is some very ugly/hacky code in https://github.com/shsteimer/IntelliVault/blob/master/src/com/razorfish/platforms/intellivault/services/impl/VaultInvokerServiceImpl.java which basically just looks for that jar file to determine if it's vault 2 or vault 3, and thus what vault class to use.  That class in the error message is the vault 2 class, so my best guess is something is going wrong with that detection logic.  Possibly your config is pointing to the wrong place, or possibly one of the jar files is missing.
