### ISSUE TITLE
RepositoryFactory is not an ImageIO SPI class error

### ISSUE THREAD

**Issue by rakhi4110** [shsteimer/IntelliVault#26]
Getting the following error since updating to IntelliJ IDEA Ultimate 2019.2

`[ERROR] import: java.lang.IllegalArgumentException: org.apache.jackrabbit.vault.fs.api.RepositoryFactory is not an ImageIO SPI class`

and the stack trace is 

```
java.lang.Throwable: [ERROR] import: java.lang.IllegalArgumentException: org.apache.jackrabbit.vault.fs.api.RepositoryFactory is not an ImageIO SPI class
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.razorfish.platforms.intellivault.services.impl.IntelliVaultServiceImpl$1.run(IntelliVaultServiceImpl.java:320)
```

**Comment by rakhi4110** [comment]
I was able to resolve this issue by forcing IntelliJ to use the Jetbrains runtime 8 instead of the runtime 11 by following the instructions provided [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)

**Comment by jon-entwistle** [comment]
This can be solved by updating to the latest version of vault-cli, e.g. https://search.maven.org/artifact/org.apache.jackrabbit.vault/vault-cli/3.2.8/jar.

**Comment by Saibul** [comment]
@jon-entwistle  yes it works with latest intellij

**Comment by rakhi4110** [comment]
Resolved by updating to the latest version of vault-cli
