### ISSUE TITLE
After connect to JCR - null pointer exception

### ISSUE THREAD

**Issue by appcia** [shsteimer/IntelliVault#3]
[ERROR] checkout: java.lang.NullPointerException: null
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
    at com.crownpartners.intellivault.services.impl.IntelliVaultServiceImpl$3.run(IntelliVaultServiceImpl.java:359)

**Comment by maozedong** [comment]
Is this issue resolved? I have the same error

**Comment by paul-wade** [comment]
Make sure that you are not putting the bin in your vault path.

I.E. use c:\filevault in the vault path setting not c:\filevault\bin

**Comment by shsteimer** [comment]
this is fixed in the latest source and will be released with v0.9.4
