### ISSUE TITLE
Integrate with Changes View

### ISSUE THREAD

**Issue by smbgood** [shsteimer/IntelliVault#6]
As an IntelliVault user, I'd like to be able to select multiple files in the Changes view and be able to push them to CRX.

**Comment by shsteimer** [comment]
I'd like to add this, but it probably falls after adding a way to support the version of vault that comes with AEM6.

**Comment by shsteimer** [comment]
won't fix.  If someone wants to contribute a PR I'd be happy to take it, but otherwise, not likely to happen.
