### ISSUE TITLE
VAULT CLASS NullPointer

### ISSUE THREAD

**Issue by AxelHo** [shsteimer/IntelliVault#7]
In AEM 6 the VAULT_CLASS is now  "org.apache.jackrabbit.vault.cli.VaultFsApp"
instead of VAULT_CLASS = "com.day.jcr.vault.cli.VaultFsApp";
Can you please change it

**Comment by shsteimer** [comment]
This is next on my priority list, but might take a bit of time as I don't want to stop supporting old versions of vault just for this, and it seems silly to make users configure it.  If I can determine exactly what version of vault it changed in, then I think I can make it seamless without requiring user intervention.

**Comment by kisonay** [comment]
Is there anyway to change this locally so that it can be used with AEM 6 until it has been updated on the plugin site?

**Comment by shsteimer** [comment]
You can simply use an older version of VLT, such as the one that ships with 5.6 and it should work fine, even with a 6.0 repository.

**Comment by AxelHo** [comment]
@kisonay 
there is a fork of IntelliVault in my repos with the new Vault_Class.
I removed the Message Dialog an log to the Console instead.
With a keymap setting it works like a charme.
Thanks to Sean!!
One Problem so far.
You cant't push a .content.xml node, you have to push the directory or the .html or whatever in there.

**Comment by shsteimer** [comment]
this is fixed in the latest commit and will be released with v0.9.4
